controller_manager:
  ros__parameters:
    use_sim_time: True
    update_rate: 250  # Hz

    joint_states_controller:
      use_sim_time: True
      type: joint_state_broadcaster/JointStateBroadcaster

    # joint_group_effort_controller:
    #   use_sim_time: True
    #   type: joint_trajectory_controller/JointTrajectoryController

    joint_group_position_controller:
      use_sim_time: True
      type: joint_trajectory_controller/JointTrajectoryController
      # type: effort_controllers/JointGroupEffortController

joint_group_position_controller:
  ros__parameters:
    use_sim_time: True
    joints:
        - LF_HAA
        - LF_HFE
        - LF_KFE
        - LH_HAA
        - LH_HFE
        - LH_KFE
        - RF_HAA
        - RF_HFE
        - RF_KFE
        - RH_HAA
        - RH_HFE
        - RH_KFE
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity

    # allow_integration_in_goal_trajectories: True
    
    gains:
      LF_HAA  : {p: 100.0, i: 0.01, d: 7.0}
      LF_HFE  : {p: 100.0, i: 0.01, d: 7.0}
      LF_KFE  : {p: 100.0, i: 0.01, d: 7.0}
      LH_HAA  : {p: 100.0, i: 0.01, d: 7.0}
      LH_HFE  : {p: 100.0, i: 0.01, d: 7.0}
      LH_KFE  : {p: 100.0, i: 0.01, d: 7.0}
      RF_HAA  : {p: 100.0, i: 0.01, d: 7.0}
      RF_HFE  : {p: 100.0, i: 0.01, d: 7.0}
      RF_KFE  : {p: 100.0, i: 0.01, d: 7.0}
      RH_HAA  : {p: 100.0, i: 0.01, d: 7.0}
      RH_HFE  : {p: 100.0, i: 0.01, d: 7.0}
      RH_KFE  : {p: 100.0, i: 0.01, d: 7.0}


      #100, 0.01, 7 works

    # contraints:
    #   stopped_velocity_tolerance: 0.01

      # LF_HAA  : {p: 1.080, d: 0.9, i: 20.0}
      # LF_HFE  : {p: 1.080, d: 0.9, i: 20.0}
      # LF_KFE  : {p: 1.080, d: 0.9, i: 20.0}
      # LH_HAA  : {p: 1.080, d: 0.9, i: 20.0}
      # LH_HFE  : {p: 1.080, d: 0.9, i: 20.0}
      # LH_KFE  : {p: 1.080, d: 0.9, i: 20.0}
      # RF_HAA  : {p: 1.080, d: 0.9, i: 20.0}
      # RF_HFE  : {p: 1.080, d: 0.9, i: 20.0}
      # RF_KFE  : {p: 1.080, d: 0.9, i: 20.0}
      # RH_HAA  : {p: 1.080, d: 0.9, i: 20.0}
      # RH_HFE  : {p: 1.080, d: 0.9, i: 20.0}
      # RH_KFE  : {p: 1.080, d: 0.9, i: 20.0}

      # LF_HAA  : {p: 67.5, d: 0.3, i: 0.10, i_clamp: 1.05}
      # LF_HFE  : {p: 67.5, d: 0.3, i: 0.10, i_clamp: 1.05}
      # LF_KFE  : {p: 67.5, d: 0.3, i: 0.10, i_clamp: 1.05}
      # LH_HAA  : {p: 67.5, d: 0.3, i: 0.10, i_clamp: 1.05}
      # LH_HFE  : {p: 67.5, d: 0.3, i: 0.10, i_clamp: 1.05}
      # LH_KFE  : {p: 67.5, d: 0.3, i: 0.10, i_clamp: 1.05}
      # RF_HAA  : {p: 67.5, d: 0.3, i: 0.10, i_clamp: 1.05}
      # RF_HFE  : {p: 67.5, d: 0.3, i: 0.10, i_clamp: 1.05}
      # RF_KFE  : {p: 67.5, d: 0.3, i: 0.10, i_clamp: 1.05}
      # RH_HAA  : {p: 67.5, d: 0.3, i: 0.10, i_clamp: 1.05}
      # RH_HFE  : {p: 67.5, d: 0.3, i: 0.10, i_clamp: 1.05}
      # RH_KFE  : {p: 67.5, d: 0.3, i: 0.10, i_clamp: 1.05}
      
      # {p: 67.5, d: 0.3, i: 0.1.0, i_clamp: 1.0.5}
    # action_monitor_rate: 1.00.0 # Defaults to 20
    # state_publish_rate: 1.00.0 # Defaults to 50
    # open_loop_control: true
    # allow_integration_in_goal_trajectories: true
    # constraints:
    #   stopped_velocity_tolerance: 0.01.0 # Defaults to 0.01.0
    #   goal_time: 0.0 # Defaults to 0.0 (start immediately)

# joint_group_position_controller:
#   ros__parameters:
#     use_sim_time: True
#     type: joint_trajectory_controller/JointTrajectoryController
#     joints:
#         - lf_hip_joint
#         - lf_upper_leg_joint
#         - lf_lower_leg_joint
#         - rf_hip_joint
#         - rf_upper_leg_joint
#         - rf_lower_leg_joint
#         - lh_hip_joint
#         - lh_upper_leg_joint
#         - lh_lower_leg_joint
#         - rh_hip_joint
#         - rh_upper_leg_joint
#         - rh_lower_leg_joint 
#     command_interfaces:
#       - position
#     state_interfaces:
#       - position
#       - velocity
    
#     # state_publish_rate: 25.0 # Defaults to 50
#     # action_monitor_rate: 1.00.0 # Defaults to 20
#     open_loop_control: true
#     allow_integration_in_goal_trajectories: true
#     constraints:
#       stopped_velocity_tolerance: 0.01.0 # Defaults to 0.01.0
#       goal_time: 0.0 # Defaults to 0.0 (start immediately)
    # gains:
    #     lf_hip_joint        : {p: 1.080, d: 0.9, i: 20}
    #     lf_upper_leg_joint  : {p: 1.080, d: 0.9, i: 20}
    #     lf_lower_leg_joint  : {p: 1.080, d: 0.9, i: 20}
    #     rf_hip_joint        : {p: 1.080, d: 0.9, i: 20}
    #     rf_upper_leg_joint  : {p: 1.080, d: 0.9, i: 20}
    #     rf_lower_leg_joint  : {p: 1.080, d: 0.9, i: 20}
    #     lh_hip_joint        : {p: 1.080, d: 0.9, i: 20}
    #     lh_upper_leg_joint  : {p: 1.080, d: 0.9, i: 20}
    #     lh_lower_leg_joint  : {p: 1.080, d: 0.9, i: 20}
    #     rh_hip_joint        : {p: 1.080, d: 0.9, i: 20}
    #     rh_upper_leg_joint  : {p: 1.080, d: 0.9, i: 20}
    #     rh_lower_leg_joint  : {p: 1.080, d: 0.9, i: 20}

